# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 773416099b18a956131ed15d396055b26cfed7cc6525dbf556ab0b04762aee7e8400e03b47969ad40e62885eee072fd8ee2bbc997833cee72bf1597b873c8232

test:
  secret_key_base: 614f5c64bfdc261802812ee579ca27636bc92a2b92057bb375ea3cf2fa5ba273f9580822eeb86fe16ef8b2da1c11f0cee117b0a2b0a9909af35de66bc604adc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
